# Starship Config

add_newline = true
command_timeout = 500
scan_timeout = 100

format = """$directory${custom.git_dirty}${custom.git_clean}$character"""

[directory]
style = "bold #7aa2f7"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

# Dirty repo - red
[custom.git_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
command = 'git branch --show-current'
style = "bold #f7768e"
format = "[󰘬 $output]($style) "

# Clean repo - purple
[custom.git_clean]
when = 'git rev-parse --git-dir &>/dev/null && test -z "$(git status --porcelain 2>/dev/null)"'
command = 'git branch --show-current'
style = "bold #bb9af7"
format = "[󰘬 $output]($style) "

[character]
success_symbol = "[➜](bold #c0caf5)"
error_symbol = "[➜](bold #f7768e)"
vimcmd_symbol = "[❮](bold #9ece6a)"

[package]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[rust]
disabled = true
[golang]
disabled = true
[git_branch]
disabled = true
[git_status]
disabled = true
